{% set name = "mxtifffile" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mxtifffile/mxtifffile-{{ version }}.tar.gz
  # Run: curl -s https://pypi.org/pypi/mxtifffile/{{ version }}/json | python -m json.tool | grep sha256
  sha256: PLACEHOLDER

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - tifffile
    - numpy
    - imagecodecs

test:
  imports:
    - mxtifffile

about:
  home: https://github.com/grenkoca/qptifffile
  license: MIT
  license_file: LICENSE
  summary: A config-driven multiplex TIFF reader supporting QPTIFF, OME-TIFF, and ImageJ formats
